const provinces = [
  { value: "1", label: "Thái Bình" },
  { value: "2", label: "Nghệ An" },
  { value: "3", label: "Hà Tĩnh" },
  { value: "4", label: "Quảng Bình" },
  { value: "5", label: "Quảng Trị" },
  { value: "6", label: "Thừa Thiên Huế" },
  { value: "7", label: "Đà Nẵng" },
  { value: "8", label: "Quảng Nam" },
  { value: "9", label: "Quảng Ngãi" },
  { value: "10", label: "Bình Định" },
  { value: "11", label: "Phú Yên" },
  { value: "12", label: "Khánh Hòa" },
  { value: "13", label: "Ninh Thuận" },
  { value: "14", label: "Bình Thuận" },
  { value: "15", label: "Hà Giang" },
  { value: "16", label: "Cao Bằng" },
  { value: "17", label: "Bắc Kạn" },
  { value: "18", label: "Tuyên Quang" },
  { value: "19", label: "Lào Cai" },
  { value: "20", label: "Yên Bái" },
  { value: "21", label: "Thái Nguyên" },
  { value: "22", label: "Lạng Sơn" },
  { value: "23", label: "Quảng Ninh" },
  { value: "24", label: "Phú Thọ" },
  { value: "25", label: "Bắc Giang" },
  { value: "26", label: "Lai Châu" },
  { value: "27", label: "Điện Biên" },
  { value: "28", label: "Sơn La" },
  { value: "29", label: "Hòa Bình" },
  { value: "30", label: "Hà Nội" },
  { value: "31", label: "Hải Phòng" },
  { value: "32", label: "Vĩnh Phúc" },
  { value: "33", label: "Bắc Ninh" },
  { value: "34", label: "Hải Dương" },
  { value: "35", label: "Hưng Yên" },
  { value: "36", label: "Thanh Hóa" },
  { value: "37", label: "Hà Nam" },
  { value: "38", label: "Nam Định" },
  { value: "39", label: "Ninh Bình" },
  { value: "40", label: "Lâm Đồng" },
  { value: "41", label: "Kon Tum" },
  { value: "42", label: "Gia Lai" },
  { value: "43", label: "Đắk Lắk" },
  { value: "44", label: "Đắk Nông" },
  { value: "45", label: "Bà Rịa - Vũng Tàu" },
  { value: "46", label: "Bình Dương" },
  { value: "47", label: "Bình Phước" },
  { value: "48", label: "Đồng Nai" },
  { value: "49", label: "Tây Ninh" },
  { value: "50", label: "Hồ Chí Minh" },
  { value: "51", label: "Cần Thơ" },
  { value: "52", label: "Long An" },
  { value: "53", label: "Tiền Giang" },
  { value: "54", label: "Bến Tre" },
  { value: "55", label: "Trà Vinh" },
  { value: "56", label: "Vĩnh Long" },
  { value: "57", label: "Đồng Tháp" },
  { value: "58", label: "An Giang" },
  { value: "59", label: "Kiên Giang" },
  { value: "60", label: "Hậu Giang" },
  { value: "61", label: "Sóc Trăng" },
  { value: "62", label: "Bạc Liêu" },
  { value: "63", label: "Cà Mau" },
];

const regexLatLng =
  /^-?([1-8]?\d(\.\d+)?|90(\.0+)?),\s*-?(180(\.0+)?|((1[0-7]\d)|(\d{1,2}))(\.\d+)?)$/;

export { provinces, regexLatLng };
