import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/redux/Provider";

const inter = Inter({ weight: "600", subsets: ["latin"] });

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
